### ISSUE TITLE
Calculation

### ISSUE THREAD

**Issue by klef-dev** [inth3wild/Loan-Calculator#1]
When a click the button to calculate, it throws an error **This page isn’t working** 405.
Please fix the calculation, and the loan-calculator.js is kind of empty.

**Comment by inth3wild** [comment]
En garde, i don't know how to fix the 405 error page.

**Comment by klef-dev** [comment]
When I click on calculate I want to be able to get the result of my loan

**Comment by klef-dev** [comment]
Come on @inth3wild you're wasting my time

**Comment by klef-dev** [comment]
Fixed it myself
